import { getStore } from '@netlify/blobs';
import { getUser, verifyRequestOrigin } from '@netlify/identity';

const STORE_NAME='agentraining-pilot';
const headers={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};
function reply(status,body){return new Response(JSON.stringify(body),{status,headers})}
function clean(v,max=500){return String(v??'').trim().slice(0,max)}
function seg(v,f='founding-pilot'){return clean(v,100).toLowerCase().replace(/[^a-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'')||f}
async function manager(req){verifyRequestOrigin(req);const u=await getUser(req);if(!u)throw Object.assign(new Error('Please sign in.'),{status:401});const r=Array.isArray(u.roles)?u.roles:[];if(!r.includes('manager')&&!r.includes('admin'))throw Object.assign(new Error('Manager access is required.'),{status:403});return{teamId:seg(u.appMetadata?.team_id),email:clean(u.email,254).toLowerCase()}}
function normalizePoint(p,i){return{id:`K${String(i+1).padStart(3,'0')}`,label:clean(p?.label,160),category:clean(p?.category,120)||'Source concept',summary:clean(p?.summary,500),sourceReference:clean(p?.sourceReference,300)||`Source excerpt ${i+1}`,importance:['core','supporting'].includes(p?.importance)?p.importance:'supporting',eligibleDepths:Array.isArray(p?.eligibleDepths)&&p.eligibleDepths.length?p.eligibleDepths.filter(x=>['Recall','Understanding','Application'].includes(x)):['Recall','Understanding'],sensitiveClaim:!!p?.sensitiveClaim}}
function provisionalPoints(record){const raw=String(record?.content||'').replace(/[ \t]+/g,' ').replace(/\r/g,'').trim();if(!raw)return[];let pieces=raw.split(/\n+|(?<=[。！？.!?])\s+/).map(x=>x.trim()).filter(x=>x.length>=35);const seen=new Set();pieces=pieces.filter(x=>{const fp=x.toLowerCase().replace(/[^a-z0-9\u3400-\u9fff]+/g,' ').replace(/\s+/g,' ').slice(0,180);if(!fp||seen.has(fp))return false;seen.add(fp);return true});if(pieces.length<8){pieces=[];for(let i=0;i<raw.length;i+=420){const x=raw.slice(i,i+520).trim();if(x.length>=80)pieces.push(x)}}const target=Math.min(28,Math.max(12,pieces.length)),step=Math.max(1,pieces.length/target),chosen=[];for(let i=0;i<target&&Math.floor(i*step)<pieces.length;i++)chosen.push(pieces[Math.floor(i*step)]);return chosen.map((x,i)=>normalizePoint({label:`Source concept ${i+1}`,category:'Source-grounded concept',summary:x,sourceReference:`Document excerpt ${i+1}`,importance:i<Math.min(8,chosen.length)?'core':'supporting',eligibleDepths:['Recall','Understanding','Application'],sensitiveClaim:/tax|7702|guarantee|securit|invest|variable|underwrit|eligib|合规|税|保证|证券|投资|变额|核保|资格/i.test(x)},i)).filter(x=>x.summary)}

export default async req=>{if(req.method!=='POST')return reply(405,{error:'POST required.'});try{const actor=await manager(req),input=await req.json().catch(()=>({})),knowledgeId=clean(input.knowledgeId||input.id,100);if(!knowledgeId)return reply(400,{error:'knowledgeId is required.'});const store=getStore({name:STORE_NAME,consistency:'strong'}),prefix=`teams/${actor.teamId}`,source=await store.get(`${prefix}/knowledge/${knowledgeId}`,{type:'json'});if(!source)return reply(404,{error:'Knowledge source not found.'});if(!source.consentConfirmed)return reply(400,{error:'Confirm organizational authorization and AI processing consent first.'});const mapKey=`${prefix}/knowledge-maps/${knowledgeId}`;if(input.action==='status'){const existing=await store.get(mapKey,{type:'json'});return existing?reply(200,{knowledgeMap:existing}):reply(404,{error:'Knowledge Map not built yet.'})}if(input.action!=='build'&&input.action!=='rebuild')return reply(400,{error:'Unsupported action.'});const existing=await store.get(mapKey,{type:'json'});if(existing?.points?.length&&existing?.version>=2)return reply(200,{knowledgeMap:existing,reused:true});const now=new Date().toISOString();if(existing?.points?.length){const points=existing.points.map((p,i)=>normalizePoint(p,i));const upgraded={...existing,version:2,points,totalPoints:points.length,canonicalStatus:'provisional-safe-upgrade',sourceFidelityPolicy:'legacy-map-preserved-no-blocking-rebuild',updatedAt:now,upgradeWarning:'Existing grounded map was preserved without a blocking rebuild. Manager review remains required.'};await store.setJSON(mapKey,upgraded);return reply(200,{knowledgeMap:upgraded,reused:true,upgradeFallback:true,warning:upgraded.upgradeWarning})}const points=provisionalPoints(source);if(points.length<3)return reply(400,{error:'Document content is too short to build a safe training map.'});const map={id:`km-${knowledgeId}`,knowledgeId,teamId:actor.teamId,title:clean(source.title,240)+' — Knowledge Map',status:'ready',canonicalStatus:'provisional-source-grounded',sourceFidelityPolicy:'direct-source-excerpts-no-blocking-ai',points,totalPoints:points.length,model:null,createdAt:now,updatedAt:now,createdBy:actor.email,version:2,upgradeWarning:'A source-grounded provisional map was created instantly to avoid gateway timeouts. Manager review remains required; semantic consolidation can run later without blocking training.'};await store.setJSON(mapKey,map);return reply(200,{knowledgeMap:map,reused:false,provisional:true,warning:map.upgradeWarning})}catch(e){console.error('knowledge-map failed',e);return reply(e?.status||500,{error:e?.message||'Knowledge Map request failed.'})}};
