import { getStore } from '@netlify/blobs';
import { getUser, verifyRequestOrigin } from '@netlify/identity';

const STORE_NAME='agentraining-pilot';
const headers={'content-type':'application/json; charset=utf-8','cache-control':'no-store'};
function reply(status,body){return new Response(JSON.stringify(body),{status,headers})}
function clean(v,max=500){return String(v??'').trim().slice(0,max)}
function seg(v,f='founding-pilot'){return clean(v,100).toLowerCase().replace(/[^a-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'')||f}
async function manager(req){verifyRequestOrigin(req);const u=await getUser(req);if(!u)throw Object.assign(new Error('Please sign in.'),{status:401});const r=Array.isArray(u.roles)?u.roles:[];if(!r.includes('manager')&&!r.includes('admin'))throw Object.assign(new Error('Manager access is required.'),{status:403});return{teamId:seg(u.appMetadata?.team_id),email:clean(u.email,254).toLowerCase()}}
function normalizePoint(p,i){return{id:`K${String(i+1).padStart(3,'0')}`,label:clean(p?.label,160),category:clean(p?.category,120)||'Source concept',summary:clean(p?.summary,700),sourceReference:clean(p?.sourceReference,300)||`Source excerpt ${i+1}`,importance:['core','supporting'].includes(p?.importance)?p.importance:'supporting',eligibleDepths:Array.isArray(p?.eligibleDepths)&&p.eligibleDepths.length?p.eligibleDepths.filter(x=>['Recall','Understanding','Application'].includes(x)):['Recall','Understanding'],sensitiveClaim:!!p?.sensitiveClaim,trainingWorthiness:Number.isFinite(Number(p?.trainingWorthiness))?Number(p.trainingWorthiness):null}}
function fingerprint(s){return String(s||'').toLowerCase().replace(/https?:\/\/\S+|www\.\S+/g,' ').replace(/\b1[-\s]?800[-\d\s()]+/g,' ').replace(/[^a-z0-9\u3400-\u9fff]+/g,' ').replace(/\s+/g,' ').trim().slice(0,220)}
function scorePiece(x){const s=String(x||''),low=s.toLowerCase();let score=0;
  if(/term life|whole life|universal life|permanent life|life insurance|annuit|premium|death benefit|cash value|beneficiar|policy|contract|suitab|replacement|illustration|underwrit|living benefit|long.?term care|critical illness|financial planning|retirement|tax|guarantee|interest|coverage|claim|insured|insurer|寿险|人寿保险|年金|保费|身故|现金价值|受益人|保单|核保|长期护理|重大疾病|退休|保障|理赔/.test(low))score+=4;
  if(/\b(if|when|unless|because|therefore|compared|versus|difference|depends|requires|may|must|should|can)\b|如果|当|除非|因为|比较|区别|取决于|必须|应该|可以/.test(low))score+=2;
  if(/\$|%|\bage\b|\byears?\b|\bmonths?\b|\b[0-9]{2,}\b|岁|年|月|百分/.test(low))score+=1;
  if(/call\s+1-|phone|telephone|website|www\.|https?:|contact us|complaint form|attach copies|mailing address|consumer hotline|拨打|电话|网址|网站|联系我们|投诉/.test(low))score-=5;
  if(s.length<55)score-=2;
  return score;
}
function provisionalPoints(record){const raw=String(record?.content||'').replace(/[ \t]+/g,' ').replace(/\r/g,'').trim();if(!raw)return[];let pieces=raw.split(/\n+|(?<=[。！？.!?])\s+/).map(x=>x.trim()).filter(x=>x.length>=35);if(pieces.length<8){pieces=[];for(let i=0;i<raw.length;i+=420){const x=raw.slice(i,i+520).trim();if(x.length>=80)pieces.push(x)}}const seen=new Set();pieces=pieces.filter(x=>{const fp=fingerprint(x);if(!fp||seen.has(fp))return false;seen.add(fp);return true});let ranked=pieces.map((text,index)=>({text,index,score:scorePiece(text)}));let worthy=ranked.filter(x=>x.score>=2);if(worthy.length<12)worthy=ranked.filter(x=>x.score>=0);worthy.sort((a,b)=>b.score-a.score||a.index-b.index);const target=Math.min(32,Math.max(12,worthy.length));const selected=worthy.slice(0,target).sort((a,b)=>a.index-b.index);return selected.map((p,i)=>normalizePoint({label:`Training concept ${i+1}`,category:'Training-worthy source concept',summary:p.text,sourceReference:`Document concept ${i+1}`,importance:p.score>=5?'core':'supporting',eligibleDepths:p.score>=5?['Recall','Understanding','Application']:p.score>=3?['Recall','Understanding']:['Recall'],sensitiveClaim:/tax|7702|guarantee|securit|invest|variable|underwrit|eligib|suitab|replacement|合规|税|保证|证券|投资|变额|核保|资格|适当性/i.test(p.text),trainingWorthiness:p.score},i)).filter(x=>x.summary)}

export default async req=>{if(req.method!=='POST')return reply(405,{error:'POST required.'});try{const actor=await manager(req),input=await req.json().catch(()=>({})),knowledgeId=clean(input.knowledgeId||input.id,100);if(!knowledgeId)return reply(400,{error:'knowledgeId is required.'});const store=getStore({name:STORE_NAME,consistency:'strong'}),prefix=`teams/${actor.teamId}`,source=await store.get(`${prefix}/knowledge/${knowledgeId}`,{type:'json'});if(!source)return reply(404,{error:'Knowledge source not found.'});if(!source.consentConfirmed)return reply(400,{error:'Confirm organizational authorization and AI processing consent first.'});const mapKey=`${prefix}/knowledge-maps/${knowledgeId}`;if(input.action==='status'){const existing=await store.get(mapKey,{type:'json'});return existing?reply(200,{knowledgeMap:existing}):reply(404,{error:'Knowledge Map not built yet.'})}if(input.action!=='build'&&input.action!=='rebuild')return reply(400,{error:'Unsupported action.'});const existing=await store.get(mapKey,{type:'json'});if(input.action==='build'&&existing?.points?.length&&existing?.version>=3)return reply(200,{knowledgeMap:existing,reused:true});const now=new Date().toISOString();const points=provisionalPoints(source);if(points.length<3)return reply(400,{error:'Document content is too short to build a safe training map.'});const map={id:`km-${knowledgeId}`,knowledgeId,teamId:actor.teamId,title:clean(source.title,240)+' — Knowledge Map',status:'ready',canonicalStatus:'v3-training-worthiness-baseline',sourceFidelityPolicy:'source-grounded-training-worthiness-filter',points,totalPoints:points.length,model:null,createdAt:existing?.createdAt||now,updatedAt:now,createdBy:actor.email,version:3,trainingWorthinessVersion:1,upgradeWarning:'Knowledge Map V3 filters navigation/contact fragments and prioritizes source concepts with training value. It remains a deterministic pilot baseline; semantic concept consolidation is the next layer and manager review remains required.'};await store.setJSON(mapKey,map);return reply(200,{knowledgeMap:map,reused:false,rebuild:!!existing,provisional:true,warning:map.upgradeWarning})}catch(e){console.error('knowledge-map failed',e);return reply(e?.status||500,{error:e?.message||'Knowledge Map request failed.'})}};
