(function () {
  const params = new URLSearchParams(window.location.search);
  const enabled = params.get('pilot') === '1';
  const NativeURLSearchParams = window.URLSearchParams;
  if (enabled && !params.get('ref')) {
    class PilotBootstrapSearchParams extends NativeURLSearchParams { get(name) { if (name === 'ref' && !super.get('ref')) return 'demo'; return super.get(name); } }
    window.URLSearchParams = PilotBootstrapSearchParams;
    window.addEventListener('DOMContentLoaded', () => { window.URLSearchParams = NativeURLSearchParams; sessionStorage.setItem('agentraining_ref','pilot'); sessionStorage.setItem('agentraining_name','Pilot User'); sessionStorage.setItem('agentraining_team','pilot'); document.getElementById('gate-welcome')?.style && (document.getElementById('gate-welcome').style.display='none'); document.getElementById('access-gate')?.style && (document.getElementById('access-gate').style.display='none'); }, {once:true});
  }
  let readyPromise, finishReady, switchHandled=false;
  const requestedLang=params.get('lang'); if(requestedLang==='en'||requestedLang==='zh')sessionStorage.setItem('agentraining_lang',requestedLang);
  const currentLang=requestedLang||sessionStorage.getItem('agentraining_lang')||((navigator.language||'').toLowerCase().startsWith('zh')?'zh':'en'); const t=(en,zh)=>currentLang==='zh'?zh:en;
  function currentUser(){return window.netlifyIdentity&&window.netlifyIdentity.currentUser()} function roles(user){return user?.app_metadata?.roles||[]}
  function removeAccountControls(){document.getElementById('pilot-account-controls')?.remove()}
  async function signOut(){removeAccountControls();try{await window.netlifyIdentity.logout()}catch(e){try{localStorage.removeItem('gotrue.user')}catch(x){}}readyPromise=null;finishReady=null;window.location.reload()}
  function mountAccountControls(user){if(!enabled||!user)return;let c=document.getElementById('pilot-account-controls');if(!c){c=document.createElement('div');c.id='pilot-account-controls';c.style.cssText='position:fixed;right:14px;bottom:14px;z-index:19000;display:flex;align-items:center;gap:9px;padding:9px 10px;background:#fff;border:1px solid #cbd5e1;border-radius:11px;box-shadow:0 8px 28px rgba(15,23,42,.18);font:12px Arial,sans-serif;color:#475569';c.innerHTML='<span id="pilot-account-email"></span><button id="pilot-sign-out" type="button" style="border:1px solid #bfdbfe;border-radius:8px;background:#eff6ff;color:#1d4ed8;padding:7px 10px;font-weight:700;cursor:pointer">'+t('Sign out','退出登录')+'</button>';document.body.appendChild(c);c.querySelector('button').onclick=signOut}c.querySelector('span').textContent=user.email||t('Signed in','已登录')}
  function showGate(message){let g=document.getElementById('pilot-auth-gate');if(!g){g=document.createElement('div');g.id='pilot-auth-gate';g.style.cssText='position:fixed;inset:0;z-index:20000;background:rgba(15,23,42,.94);display:flex;align-items:center;justify-content:center;padding:24px;font-family:Arial,sans-serif';g.innerHTML='<div style="width:100%;max-width:460px;background:#fff;border-radius:18px;padding:32px"><h1 style="text-align:center">AgentTraining.ai Pilot</h1><p id="pilot-auth-message" style="color:#64748b;text-align:center"></p><form id="pilot-auth-form"><input id="pilot-auth-email" type="email" placeholder="Email" required style="width:100%;padding:12px;margin:8px 0"><input id="pilot-auth-password" type="password" placeholder="Password" required style="width:100%;padding:12px;margin:8px 0"><button type="submit" style="width:100%;padding:13px;background:#1a56db;color:white;border:0;border-radius:9px">'+t('Sign in securely','安全登录')+'</button><p id="pilot-auth-status" style="color:#b91c1c;text-align:center"></p></form></div>';document.body.appendChild(g);g.querySelector('form').onsubmit=async e=>{e.preventDefault();try{const u=await window.netlifyIdentity.gotrue.login(g.querySelector('#pilot-auth-email').value.trim(),g.querySelector('#pilot-auth-password').value,true);await u.jwt();if(finishReady)finishReady(u);else location.reload()}catch(err){g.querySelector('#pilot-auth-status').textContent=err.message||t('Sign-in failed','登录失败')}}}g.querySelector('#pilot-auth-message').textContent=message;g.style.display='flex'}
  function hideGate(){const g=document.getElementById('pilot-auth-gate');if(g)g.style.display='none'}
  async function ready(requiredRole){if(!enabled)return null;if(!window.netlifyIdentity)throw new Error(t('Pilot sign-in could not be loaded.','无法载入试用登录功能。'));if(!switchHandled&&params.get('switch')==='1'){switchHandled=true;window.netlifyIdentity.init();try{await window.netlifyIdentity.logout()}catch(e){}readyPromise=null;finishReady=null}if(!readyPromise){readyPromise=new Promise(resolve=>{window.netlifyIdentity.init();const finish=user=>{hideGate();mountAccountControls(user);resolve(user)};finishReady=finish;const u=currentUser();if(u)Promise.resolve(u.jwt()).then(()=>finish(u)).catch(()=>showGate(t('Please sign in again.','请重新登录。')));else showGate(t('Please sign in with your invited Pilot account.','请使用受邀请的试用账号登录。'))})}const u=await readyPromise;if(requiredRole&&!roles(u).includes(requiredRole)&&!roles(u).includes('admin'))throw new Error(t('This page requires the '+requiredRole+' role.','此页面需要相应权限。'));return u}
  async function token(requiredRole){const user=await ready(requiredRole);if(!user||typeof user.jwt!=='function')throw new Error(t('Secure Pilot token is unavailable.','安全访问凭证不可用。'));return user.jwt()}
  async function request(resource,options={}){const {requiredRole,query,...fetchOptions}=options;const authToken=await token(requiredRole);const q=new URLSearchParams({resource});Object.entries(query||{}).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')q.set(k,String(v))});const response=await fetch('/.netlify/functions/pilot-data?'+q,{...fetchOptions,headers:{'content-type':'application/json',authorization:'Bearer '+authToken,...(fetchOptions.headers||{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||t('Pilot cloud request failed ('+response.status+').','试用云端请求失败（'+response.status+'）。'));return body}
  window.PilotCloud={enabled,ready,token,request,currentUser,signOut};
  if(enabled){const s=document.createElement('script');s.src='/openai-voice.js?v=20260817-openai1';s.defer=true;document.head.appendChild(s)}
})();